"""
URL configuration for myproject project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

from student_registration import views

urlpatterns = [
    path(
        "student_registration/send_confirmation_email",
        views.send_confirmation_email,
        name="send_confirmation_email",
    ),
    path("student_registration/signup", views.signup, name="signup"),
    path("student_registration/login", views.login, name="login"),
    path(
        "student_registration/add_student_new_first_civil1_admin",
        views.add_student_new_first_civil1_admin,
        name="add_student_new_first_civil1_admin",
    ),
    path(
        "student_registration/exampassed_list",
        views.exampassed_list,
        name="exampassed_list",
    ),
    path(
        "student_registration/delete_document_exam_result/<int:student_id>",
        views.delete_document_exam_result,
        name="delete_document",
    ),
    path(
        "student_registration/update_document_exam_result/<int:student_id>",
        views.update_document_exam_result,
        name="update_document_exam_result",
    ),
    path(
        "student_registration/student_list_new_first_civil",
        views.student_list_new_first_civil,
        name="student_list_new_first_civil",
    ),
    path(
        "student_registration/update_document_new_first_civil/<int:student_id>",
        views.update_document_new_first_civil,
        name="update_document_new_first_civil",
    ),
    path(
        "student_registration/delete_document_new_first_civil/<int:student_id>",
        views.delete_document_new_first_civil,
        name="delete_document_new_first_civil",
    ),
    path(
        "student_registration/add_student_new_first_civil_admin",
        views.add_student_new_first_civil_admin,
        name="add_student_new_first_civil_admin",
    ),
    path(
        "student_registration/view_first_civil_new/<int:student_id>",
        views.view_first_civil_new,
        name="view_first_civil_new",
    ),
    path(
        "student_registration/first_civil_list",
        views.student_list_first_civil,
        name="first_civil_list",
    ),
    path(
        "student_registration/first_ec_list",
        views.student_list_first_ec,
        name="first_ec_list",
    ),
    path(
        "student_registration/first_ep_list",
        views.student_list_first_ep,
        name="first_ep_list",
    ),
    path(
        "student_registration/first_it_list",
        views.student_list_first_it,
        name="first_it_list",
    ),
    path(
        "student_registration/first_mechanical_list",
        views.student_list_first_mechanical,
        name="first_mechanical_list",
    ),
    path(
        "student_registration/delete_document1/<int:student_id>",
        views.delete_document1,
        name="delete_document1",
    ),
    path(
        "student_registration/update_document1/<int:student_id>",
        views.update_document1,
        name="update_document1",
    ),
    path(
        "student_registration/delete_document_old_first_ec/<int:student_id>",
        views.delete_document_old_first_ec,
        name="delete_document_old_first_ec",
    ),
    path(
        "student_registration/update_document_old_first_ec/<int:student_id>",
        views.update_document_old_first_ec,
        name="update_document_old_first_ec",
    ),
    path(
        "student_registration/delete_document_old_first_ep/<int:student_id>",
        views.delete_document_old_first_ep,
        name="delete_document_old_first_ep",
    ),
    path(
        "student_registration/update_document_old_first_ep/<int:student_id>",
        views.update_document_old_first_ep,
        name="update_document_old_first_ep",
    ),
    path(
        "student_registration/delete_document_old_first_it/<int:student_id>",
        views.delete_document_old_first_it,
        name="delete_document_old_first_it",
    ),
    path(
        "student_registration/update_document_old_first_it/<int:student_id>",
        views.update_document_old_first_it,
        name="update_document_old_first_it",
    ),
    path(
        "student_registration/delete_document_old_first_mechanical/<int:student_id>",
        views.delete_document_old_first_mechanical,
        name="delete_document_old_first_mechanical",
    ),
    path(
        "student_registration/update_document_old_first_mechanical/<int:student_id>",
        views.update_document_old_first_mechanical,
        name="update_document_old_first_mechanical",
    ),
    path(
        "student_registration/add_student_old_first_civil",
        views.add_student_old_first_civil,
        name="add_student_old_first_civil",
    ),
    path(
        "student_registration/add_student_old_first_ec",
        views.add_student_old_first_ec,
        name="add_student_old_first_ec",
    ),
    path(
        "student_registration/add_student_old_first_ep",
        views.add_student_old_first_ep,
        name="add_student_old_first_ep",
    ),
    path(
        "student_registration/add_student_old_first_it",
        views.add_student_old_first_it,
        name="add_student_old_first_it",
    ),
    path(
        "student_registration/add_student_old_first_mechanical",
        views.add_student_old_first_mechanical,
        name="add_student_old_first_mechanical",
    ),
    path(
        "student_registration/student_list_old_second_civil",
        views.student_list_old_second_civil,
        name="student_list_old_second_civil",
    ),
    path(
        "student_registration/student_list_old_second_ec",
        views.student_list_old_second_ec,
        name="student_list_old_second_ec",
    ),
    path(
        "student_registration/student_list_old_second_ep",
        views.student_list_old_second_ep,
        name="student_list_old_second_ep",
    ),
    path(
        "student_registration/student_list_old_second_it",
        views.student_list_old_second_it,
        name="student_list_old_second_it",
    ),
    path(
        "student_registration/student_list_old_second_me",
        views.student_list_old_second_me,
        name="student_list_old_second_me",
    ),
    path(
        "student_registration/add_student_old_second_civil_admin",
        views.add_student_old_second_civil_admin,
        name="add_student_old_second_civil_admin",
    ),
    path(
        "student_registration/add_student_old_second_ec_admin",
        views.add_student_old_second_ec_admin,
        name="add_student_old_second_ec_admin",
    ),
    path(
        "student_registration/add_student_old_second_ep_admin",
        views.add_student_old_second_ep_admin,
        name="add_student_old_second_ep_admin",
    ),
    path(
        "student_registration/add_student_old_second_it_admin",
        views.add_student_old_second_it_admin,
        name="add_student_old_second_it_admin",
    ),
    path(
        "student_registration/add_student_old_second_me_admin",
        views.add_student_old_second_me_admin,
        name="add_student_old_second_me_admin",
    ),
    path(
        "student_registration/delete_document_old_second_civil/<int:student_id>",
        views.delete_document_old_second_civil,
        name="delete_document_old_second_civil",
    ),
    path(
        "student_registration/update_document_old_second_civil/<int:student_id>",
        views.update_document_old_second_civil,
        name="update_document_old_second_civil",
    ),
    path(
        "student_registration/delete_document_old_second_ec/<int:student_id>",
        views.delete_document_old_second_ec,
        name="delete_document_old_second_ec",
    ),
    path(
        "student_registration/update_document_old_second_ec/<int:student_id>",
        views.update_document_old_second_ec,
        name="update_document_old_second_ec",
    ),
    path(
        "student_registration/delete_document_old_second_ep/<int:student_id>",
        views.delete_document_old_second_ep,
        name="delete_document_old_second_ep",
    ),
    path(
        "student_registration/update_document_old_second_ep/<int:student_id>",
        views.update_document_old_second_ep,
        name="update_document_old_second_ep",
    ),
    path(
        "student_registration/delete_document_old_second_it/<int:student_id>",
        views.delete_document_old_second_it,
        name="delete_document_old_second_it",
    ),
    path(
        "student_registration/update_document_old_second_it/<int:student_id>",
        views.update_document_old_second_it,
        name="update_document_old_second_it",
    ),
    path(
        "student_registration/delete_document_old_second_me/<int:student_id>",
        views.delete_document_old_second_me,
        name="delete_document_old_second_me",
    ),
    path(
        "student_registration/update_document_old_second_me/<int:student_id>",
        views.update_document_old_second_me,
        name="update_document_old_second_me",
    ),
    path(
        "student_registration/student_list_new_second_civil",
        views.student_list_new_second_civil,
        name="student_list_new_second_civil",
    ),
    path(
        "student_registration/add_student_new_second_civil_admin",
        views.add_student_new_second_civil_admin,
        name="add_student_new_second_civil_admin",
    ),
    path(
        "student_registration/view_second_civil_new/<int:student_id>",
        views.view_second_civil_new,
        name="view_second_civil_new",
    ),
    path(
        "student_registration/delete_document/<int:student_id>",
        views.delete_document,
        name="delete_document",
    ),
    path(
        "student_registration/update_document/<int:student_id>",
        views.update_document,
        name="update_document",
    ),
    path(
        "student_registration/student_list_new_second_ec",
        views.student_list_new_second_ec,
        name="student_list_new_second_ec",
    ),
    path(
        "student_registration/add_student_new_second_ec_admin",
        views.add_student_new_second_ec_admin,
        name="add_student_new_second_ec_admin",
    ),
    path(
        "student_registration/view_second_ec_new/<int:student_id>",
        views.view_second_ec_new,
        name="view_second_ec_new",
    ),
    path(
        "student_registration/delete_document_new_second_ec/<int:student_id>",
        views.delete_document_new_second_ec,
        name="delete_document_new_second_ec",
    ),
    path(
        "student_registration/update_document_new_second_ec/<int:student_id>",
        views.update_document_new_second_ec,
        name="update_document_new_second_ec",
    ),
    path(
        "student_registration/student_list_new_second_ep",
        views.student_list_new_second_ep,
        name="student_list_new_second_ep",
    ),
    path(
        "student_registration/add_student_new_second_ep_admin",
        views.add_student_new_second_ep_admin,
        name="add_student_new_second_ep_admin",
    ),
    path(
        "student_registration/view_second_ep_new/<int:student_id>",
        views.view_second_ep_new,
        name="view_second_ep_new",
    ),
    path(
        "student_registration/delete_document_new_second_ep/<int:student_id>",
        views.delete_document_new_second_ep,
        name="delete_document_new_second_ep",
    ),
    path(
        "student_registration/update_document_new_second_ep/<int:student_id>",
        views.update_document_new_second_ep,
        name="update_document_new_second_ep",
    ),
    path(
        "student_registration/student_list_new_second_it",
        views.student_list_new_second_it,
        name="student_list_new_second_it",
    ),
    path(
        "student_registration/add_student_new_second_it_admin",
        views.add_student_new_second_it_admin,
        name="add_student_new_second_it_admin",
    ),
    path(
        "student_registration/view_second_it_new/<int:student_id>",
        views.view_second_it_new,
        name="view_second_it_new",
    ),
    path(
        "student_registration/delete_document_new_second_it/<int:student_id>",
        views.delete_document_new_second_it,
        name="delete_document_new_second_it",
    ),
    path(
        "student_registration/update_document_new_second_it/<int:student_id>",
        views.update_document_new_second_it,
        name="update_document_new_second_it",
    ),
    path(
        "student_registration/student_list_new_second_me",
        views.student_list_new_second_me,
        name="student_list_new_second_me",
    ),
    path(
        "student_registration/add_student_new_second_me_admin",
        views.add_student_new_second_me_admin,
        name="add_student_new_second_me_admin",
    ),
    path(
        "student_registration/view_second_me_new/<int:student_id>",
        views.view_second_me_new,
        name="view_second_me_new",
    ),
    path(
        "student_registration/delete_document_new_second_me/<int:student_id>",
        views.delete_document_new_second_me,
        name="delete_document_new_second_me",
    ),
    path(
        "student_registration/update_document_new_second_me/<int:student_id>",
        views.update_document_new_second_me,
        name="update_document_new_second_me",
    ),
    path(
        "student_registration/student_list_new_third_ec",
        views.student_list_new_third_ec,
        name="student_list_new_third_ec",
    ),
    path(
        "student_registration/add_student_new_third_ec_admin",
        views.add_student_new_third_ec_admin,
        name="add_student_new_third_ec_admin",
    ),
    path(
        "student_registration/view_third_ec_new/<int:student_id>",
        views.view_third_ec_new,
        name="view_third_ec_new",
    ),
    path(
        "student_registration/delete_document_new_third_ec/<int:student_id>",
        views.delete_document_new_third_ec,
        name="delete_document_new_third_ec",
    ),
    path(
        "student_registration/update_document_new_third_ec/<int:student_id>",
        views.update_document_new_third_ec,
        name="update_document_new_third_ec",
    ),
    path(
        "student_registration/student_list_new_third_ep",
        views.student_list_new_third_ep,
        name="student_list_new_third_ep",
    ),
    path(
        "student_registration/add_student_new_third_ep_admin",
        views.add_student_new_third_ep_admin,
        name="add_student_new_third_ep_admin",
    ),
    path(
        "student_registration/view_third_ep_new/<int:student_id>",
        views.view_third_ep_new,
        name="view_third_ep_new",
    ),
    path(
        "student_registration/delete_document_new_third_ep/<int:student_id>",
        views.delete_document_new_third_ep,
        name="delete_document_new_third_ep",
    ),
    path(
        "student_registration/update_document_new_third_ep/<int:student_id>",
        views.update_document_new_third_ep,
        name="update_document_new_third_ep",
    ),
    path(
        "student_registration/student_list_new_third_it",
        views.student_list_new_third_it,
        name="student_list_new_third_it",
    ),
    path(
        "student_registration/add_student_new_third_it_admin",
        views.add_student_new_third_it_admin,
        name="add_student_new_third_it_admin",
    ),
    path(
        "student_registration/view_third_it_new/<int:student_id>",
        views.view_third_it_new,
        name="view_third_it_new",
    ),
    path(
        "student_registration/delete_document_new_third_it/<int:student_id>",
        views.delete_document_new_third_it,
        name="delete_document_new_third_it",
    ),
    path(
        "student_registration/update_document_new_third_it/<int:student_id>",
        views.update_document_new_third_it,
        name="update_document_new_third_it",
    ),
    path(
        "student_registration/student_list_new_third_me",
        views.student_list_new_third_me,
        name="student_list_new_third_me",
    ),
    path(
        "student_registration/add_student_new_third_me_admin",
        views.add_student_new_third_me_admin,
        name="add_student_new_third_me_admin",
    ),
    path(
        "student_registration/view_third_me_new/<int:student_id>",
        views.view_third_me_new,
        name="view_third_me_new",
    ),
    path(
        "student_registration/delete_document_new_third_me/<int:student_id>",
        views.delete_document_new_third_me,
        name="delete_document_new_third_me",
    ),
    path(
        "student_registration/update_document_new_third_me/<int:student_id>",
        views.update_document_new_third_me,
        name="update_document_new_third_me",
    ),
    path(
        "student_registration/student_list_new_fourth_ec",
        views.student_list_new_fourth_ec,
        name="student_list_new_fourth_ec",
    ),
    path(
        "student_registration/add_student_new_fourth_ec_admin",
        views.add_student_new_fourth_ec_admin,
        name="add_student_new_fourth_ec_admin",
    ),
    path(
        "student_registration/view_fourth_ec_new/<int:student_id>",
        views.view_fourth_ec_new,
        name="view_fourth_ec_new",
    ),
    path(
        "student_registration/delete_document_new_fourth_ec/<int:student_id>",
        views.delete_document_new_fourth_ec,
        name="delete_document_new_fourth_ec",
    ),
    path(
        "student_registration/update_document_new_fourth_ec/<int:student_id>",
        views.update_document_new_fourth_ec,
        name="update_document_new_fourth_ec",
    ),
    path(
        "student_registration/student_list_new_fourth_ep",
        views.student_list_new_fourth_ep,
        name="student_list_new_fourth_ep",
    ),
    path(
        "student_registration/add_student_new_fourth_ep_admin",
        views.add_student_new_fourth_ep_admin,
        name="add_student_new_fourth_ep_admin",
    ),
    path(
        "student_registration/view_fourth_ep_new/<int:student_id>",
        views.view_fourth_ep_new,
        name="view_fourth_ep_new",
    ),
    path(
        "student_registration/delete_document_new_fourth_ep/<int:student_id>",
        views.delete_document_new_fourth_ep,
        name="delete_document_new_fourth_ep",
    ),
    path(
        "student_registration/update_document_new_fourth_ep/<int:student_id>",
        views.update_document_new_fourth_ep,
        name="update_document_new_fourth_ep",
    ),
    path(
        "student_registration/student_list_new_fourth_it",
        views.student_list_new_fourth_it,
        name="student_list_new_fourth_it",
    ),
    path(
        "student_registration/add_student_new_fourth_it_admin",
        views.add_student_new_fourth_it_admin,
        name="add_student_new_fourth_it_admin",
    ),
    path(
        "student_registration/view_fourth_it_new/<int:student_id>",
        views.view_fourth_it_new,
        name="view_fourth_it_new",
    ),
    path(
        "student_registration/delete_document_new_fourth_it/<int:student_id>",
        views.delete_document_new_fourth_it,
        name="delete_document_new_fourth_it",
    ),
    path(
        "student_registration/update_document_new_fourth_it/<int:student_id>",
        views.update_document_new_fourth_it,
        name="update_document_new_fourth_it",
    ),
    path(
        "student_registration/student_list_new_fourth_me",
        views.student_list_new_fourth_me,
        name="student_list_new_fourth_me",
    ),
    path(
        "student_registration/add_student_new_fourth_me_admin",
        views.add_student_new_fourth_me_admin,
        name="add_student_new_fourth_me_admin",
    ),
    path(
        "student_registration/view_fourth_me_new/<int:student_id>",
        views.view_fourth_me_new,
        name="view_fourth_me_new",
    ),
    path(
        "student_registration/delete_document_new_fourth_me/<int:student_id>",
        views.delete_document_new_fourth_me,
        name="delete_document_new_fourth_me",
    ),
    path(
        "student_registration/update_document_new_fourth_me/<int:student_id>",
        views.update_document_new_fourth_me,
        name="update_document_new_fourth_me",
    ),
    path(
        "student_registration/student_list_new_fifth_ec",
        views.student_list_new_fifth_ec,
        name="student_list_new_fifth_ec",
    ),
    path(
        "student_registration/add_student_new_fifth_ec_admin",
        views.add_student_new_fifth_ec_admin,
        name="add_student_new_fifth_ec_admin",
    ),
    path(
        "student_registration/view_fifth_ec_new/<int:student_id>",
        views.view_fifth_ec_new,
        name="view_fifth_ec_new",
    ),
    path(
        "student_registration/delete_document_new_fifth_ec/<int:student_id>",
        views.delete_document_new_fifth_ec,
        name="delete_document_new_fifth_ec",
    ),
    path(
        "student_registration/update_document_new_fifth_ec/<int:student_id>",
        views.update_document_new_fifth_ec,
        name="update_document_new_fifth_ec",
    ),
    path(
        "student_registration/student_list_new_fifth_ep",
        views.student_list_new_fifth_ep,
        name="student_list_new_fifth_ep",
    ),
    path(
        "student_registration/add_student_new_fifth_ep_admin",
        views.add_student_new_fifth_ep_admin,
        name="add_student_new_fifth_ep_admin",
    ),
    path(
        "student_registration/view_fifth_ep_new/<int:student_id>",
        views.view_fifth_ep_new,
        name="view_fifth_ep_new",
    ),
    path(
        "student_registration/delete_document_new_fifth_ep/<int:student_id>",
        views.delete_document_new_fifth_ep,
        name="delete_document_new_fifth_ep",
    ),
    path(
        "student_registration/update_document_new_fifth_ep/<int:student_id>",
        views.update_document_new_fifth_ep,
        name="update_document_new_fifth_ep",
    ),
    path(
        "student_registration/student_list_new_fifth_it",
        views.student_list_new_fifth_it,
        name="student_list_new_fifth_it",
    ),
    path(
        "student_registration/add_student_new_fifth_it_admin",
        views.add_student_new_fifth_it_admin,
        name="add_student_new_fifth_it_admin",
    ),
    path(
        "student_registration/view_fifth_it_new/<int:student_id>",
        views.view_fifth_it_new,
        name="view_fifth_it_new",
    ),
    path(
        "student_registration/delete_document_new_fifth_it/<int:student_id>",
        views.delete_document_new_fifth_it,
        name="delete_document_new_fifth_it",
    ),
    path(
        "student_registration/update_document_new_fifth_it/<int:student_id>",
        views.update_document_new_fifth_it,
        name="update_document_new_fifth_it",
    ),
    path(
        "student_registration/student_list_new_fifth_me",
        views.student_list_new_fifth_me,
        name="student_list_new_fifth_me",
    ),
    path(
        "student_registration/add_student_new_fifth_me_admin",
        views.add_student_new_fifth_me_admin,
        name="add_student_new_fifth_me_admin",
    ),
    path(
        "student_registration/view_fifth_me_new/<int:student_id>",
        views.view_fifth_me_new,
        name="view_fifth_me_new",
    ),
    path(
        "student_registration/delete_document_new_fifth_me/<int:student_id>",
        views.delete_document_new_fifth_me,
        name="delete_document_new_fifth_me",
    ),
    path(
        "student_registration/update_document_new_fifth_me/<int:student_id>",
        views.update_document_new_fifth_me,
        name="update_document_new_fifth_me",
    ),
    path(
        "student_registration/student_list_new_sixth_ec",
        views.student_list_new_sixth_ec,
        name="student_list_new_sixth_ec",
    ),
    path(
        "student_registration/add_student_new_sixth_ec_admin",
        views.add_student_new_sixth_ec_admin,
        name="add_student_new_sixth_ec_admin",
    ),
    path(
        "student_registration/view_sixth_ec_new/<int:student_id>",
        views.view_sixth_ec_new,
        name="view_sixth_ec_new",
    ),
    path(
        "student_registration/delete_document_new_sixth_ec/<int:student_id>",
        views.delete_document_new_sixth_ec,
        name="delete_document_new_sixth_ec",
    ),
    path(
        "student_registration/update_document_new_sixth_ec/<int:student_id>",
        views.update_document_new_sixth_ec,
        name="update_document_new_sixth_ec",
    ),
    path(
        "student_registration/student_list_new_sixth_ep",
        views.student_list_new_sixth_ep,
        name="student_list_new_sixth_ep",
    ),
    path(
        "student_registration/add_student_new_sixth_ep_admin",
        views.add_student_new_sixth_ep_admin,
        name="add_student_new_sixth_ep_admin",
    ),
    path(
        "student_registration/view_sixth_ep_new/<int:student_id>",
        views.view_sixth_ep_new,
        name="view_sixth_ep_new",
    ),
    path(
        "student_registration/delete_document_new_sixth_ep/<int:student_id>",
        views.delete_document_new_sixth_ep,
        name="delete_document_new_sixth_ep",
    ),
    path(
        "student_registration/update_document_new_sixth_ep/<int:student_id>",
        views.update_document_new_sixth_ep,
        name="update_document_new_sixth_ep",
    ),
    path(
        "student_registration/student_list_new_sixth_it",
        views.student_list_new_sixth_it,
        name="student_list_new_sixth_it",
    ),
    path(
        "student_registration/add_student_new_sixth_it_admin",
        views.add_student_new_sixth_it_admin,
        name="add_student_new_sixth_it_admin",
    ),
    path(
        "student_registration/view_sixth_it_new/<int:student_id>",
        views.view_sixth_it_new,
        name="view_sixth_it_new",
    ),
    path(
        "student_registration/delete_document_new_sixth_it/<int:student_id>",
        views.delete_document_new_sixth_it,
        name="delete_document_new_sixth_it",
    ),
    path(
        "student_registration/update_document_new_sixth_it/<int:student_id>",
        views.update_document_new_sixth_it,
        name="update_document_new_sixth_it",
    ),
    path(
        "student_registration/student_list_new_sixth_me",
        views.student_list_new_sixth_me,
        name="student_list_new_sixth_me",
    ),
    path(
        "student_registration/add_student_new_sixth_me_admin",
        views.add_student_new_sixth_me_admin,
        name="add_student_new_sixth_me_admin",
    ),
    path(
        "student_registration/view_sixth_me_new/<int:student_id>",
        views.view_sixth_me_new,
        name="view_sixth_me_new",
    ),
    path(
        "student_registration/delete_document_new_sixth_me/<int:student_id>",
        views.delete_document_new_sixth_me,
        name="delete_document_new_sixth_me",
    ),
    path(
        "student_registration/update_document_new_sixth_me/<int:student_id>",
        views.update_document_new_sixth_me,
        name="update_document_new_sixth_me",
    ),
    path(
        "student_registration/student_list_third_civil",
        views.student_list_third_civil,
        name="student_list_third_civil",
    ),
    path(
        "student_registration/student_list_old_third_ec",
        views.student_list_old_third_ec,
        name="student_list_old_third_ec",
    ),
    path(
        "student_registration/student_list_old_third_ep",
        views.student_list_old_third_ep,
        name="student_list_old_third_ep",
    ),
    path(
        "student_registration/student_list_old_third_it",
        views.student_list_old_third_it,
        name="student_list_old_third_it",
    ),
    path(
        "student_registration/student_list_old_third_me",
        views.student_list_old_third_me,
        name="student_list_old_third_me",
    ),
    path(
        "student_registration/add_student_old_third_civil_admin",
        views.add_student_old_third_civil_admin,
        name="add_student_old_third_civil_admin",
    ),
    path(
        "student_registration/delete_document_old_third_civil/<int:student_id>",
        views.delete_document_old_third_civil,
        name="delete_document_old_second_civil",
    ),
    path(
        "student_registration/update_document_old_third_civil/<int:student_id>",
        views.update_document_old_third_civil,
        name="update_document_old_third_civil",
    ),
    path(
        "student_registration/add_student_old_third_ec_admin",
        views.add_student_old_third_ec_admin,
        name="add_student_old_third_ec_admin",
    ),
    path(
        "student_registration/delete_document_old_third_ec/<int:student_id>",
        views.delete_document_old_third_ec,
        name="delete_document_old_third_ec",
    ),
    path(
        "student_registration/update_document_old_third_ec/<int:student_id>",
        views.update_document_old_third_ec,
        name="update_document_old_third_ec",
    ),
    path(
        "student_registration/add_student_old_third_ep_admin",
        views.add_student_old_third_ep_admin,
        name="add_student_old_third_ep_admin",
    ),
    path(
        "student_registration/delete_document_old_third_ep/<int:student_id>",
        views.delete_document_old_third_ep,
        name="delete_document_old_third_ep",
    ),
    path(
        "student_registration/update_document_old_third_ep/<int:student_id>",
        views.update_document_old_third_ep,
        name="update_document_old_third_ep",
    ),
    path(
        "student_registration/add_student_old_third_it_admin",
        views.add_student_old_third_it_admin,
        name="add_student_old_third_it_admin",
    ),
    path(
        "student_registration/delete_document_old_third_it/<int:student_id>",
        views.delete_document_old_third_it,
        name="delete_document_old_third_it",
    ),
    path(
        "student_registration/update_document_old_third_it/<int:student_id>",
        views.update_document_old_third_it,
        name="update_document_old_third_it",
    ),
    path(
        "student_registration/add_student_old_third_me_admin",
        views.add_student_old_third_me_admin,
        name="add_student_old_third_me_admin",
    ),
    path(
        "student_registration/delete_document_old_third_me/<int:student_id>",
        views.delete_document_old_third_me,
        name="delete_document_old_third_me",
    ),
    path(
        "student_registration/update_document_old_third_me/<int:student_id>",
        views.update_document_old_third_me,
        name="update_document_old_third_me",
    ),
    path(
        "student_registration/student_list_new_third_civil",
        views.student_list_new_third_civil,
        name="student_list_new_third_civil",
    ),
    path(
        "student_registration/add_student_new_third_civil_admin",
        views.add_student_new_third_civil_admin,
        name="add_student_new_second_civil_admin",
    ),
    path(
        "student_registration/view_third_civil_new/<int:student_id>",
        views.view_third_civil_new,
        name="view_third_civil_new",
    ),
    path(
        "student_registration/delete_document_new_third_civil/<int:student_id>",
        views.delete_document_new_third_civil,
        name="delete_document_new_third_civil",
    ),
    path(
        "student_registration/update_document_New_third_civil/<int:student_id>",
        views.update_document_New_third_civil,
        name="update_document_New_third_civil",
    ),
    path(
        "student_registration/student_list_fourth_civil",
        views.student_list_fourth_civil,
        name="student_list_fourth_civil",
    ),
    path(
        "student_registration/student_list_old_fourth_ec",
        views.student_list_old_fourth_ec,
        name="student_list_old_fourth_ec",
    ),
    path(
        "student_registration/student_list_old_fourth_ep",
        views.student_list_old_fourth_ep,
        name="student_list_old_fourth_ep",
    ),
    path(
        "student_registration/student_list_old_fourth_it",
        views.student_list_old_fourth_it,
        name="student_list_old_fourth_it",
    ),
    path(
        "student_registration/student_list_old_fourth_me",
        views.student_list_old_fourth_me,
        name="student_list_old_fourth_me",
    ),
    path(
        "student_registration/add_student_old_fourth_civil_admin",
        views.add_student_old_fourth_civil_admin,
        name="add_student_old_fourth_civil_admin",
    ),
    path(
        "student_registration/delete_document_old_fourth_civil/<int:student_id>",
        views.delete_document_old_fourth_civil,
        name="delete_document_old_fourth_civil",
    ),
    path(
        "student_registration/update_document_old_fourth_civil/<int:student_id>",
        views.update_document_old_fourth_civil,
        name="update_document_old_fourth_civil",
    ),
    path(
        "student_registration/add_student_old_fourth_ec_admin",
        views.add_student_old_fourth_ec_admin,
        name="add_student_old_fourth_ec_admin",
    ),
    path(
        "student_registration/delete_document_old_fourth_ec/<int:student_id>",
        views.delete_document_old_fourth_ec,
        name="delete_document_old_fourth_ec",
    ),
    path(
        "student_registration/update_document_old_fourth_ec/<int:student_id>",
        views.update_document_old_fourth_ec,
        name="update_document_old_fourth_ec",
    ),
    path(
        "student_registration/add_student_old_fourth_ep_admin",
        views.add_student_old_fourth_ep_admin,
        name="add_student_old_fourth_ep_admin",
    ),
    path(
        "student_registration/delete_document_old_fourth_ep/<int:student_id>",
        views.delete_document_old_fourth_ep,
        name="delete_document_old_fourth_ep",
    ),
    path(
        "student_registration/update_document_old_fourth_ep/<int:student_id>",
        views.update_document_old_fourth_ep,
        name="update_document_old_fourth_ep",
    ),
    path(
        "student_registration/add_student_old_fourth_it_admin",
        views.add_student_old_fourth_it_admin,
        name="add_student_old_fourth_it_admin",
    ),
    path(
        "student_registration/delete_document_old_fourth_it/<int:student_id>",
        views.delete_document_old_fourth_it,
        name="delete_document_old_fourth_it",
    ),
    path(
        "student_registration/update_document_old_fourth_it/<int:student_id>",
        views.update_document_old_fourth_it,
        name="update_document_old_fourth_it",
    ),
    path(
        "student_registration/add_student_old_fourth_me_admin",
        views.add_student_old_fourth_me_admin,
        name="add_student_old_fourth_me_admin",
    ),
    path(
        "student_registration/delete_document_old_fourth_me/<int:student_id>",
        views.delete_document_old_fourth_me,
        name="delete_document_old_fourth_me",
    ),
    path(
        "student_registration/update_document_old_fourth_me/<int:student_id>",
        views.update_document_old_fourth_me,
        name="update_document_old_fourth_me",
    ),
    path(
        "student_registration/student_list_new_fourth_civil",
        views.student_list_new_fourth_civil,
        name="student_list_new_fourth_civil",
    ),
    path(
        "student_registration/add_student_new_fourth_civil_admin",
        views.add_student_new_fourth_civil_admin,
        name="add_student_new_fourth_civil_admin",
    ),
    path(
        "student_registration/view_fourth_civil_new/<int:student_id>",
        views.view_fourth_civil_new,
        name="view_fourth_civil_new",
    ),
    path(
        "student_registration/delete_document_new_fourth_civil/<int:student_id>",
        views.delete_document_new_fourth_civil,
        name="delete_document_new_fourth_civil",
    ),
    path(
        "student_registration/update_document_new_fourth_civil/<int:student_id>",
        views.update_document_new_fourth_civil,
        name="update_document_new_fourth_civil",
    ),
    path(
        "student_registration/student_list_new_fifth_civil",
        views.student_list_new_fifth_civil,
        name="student_list_new_fifth_civil",
    ),
    path(
        "student_registration/add_student_new_fifth_civil_admin",
        views.add_student_new_fifth_civil_admin,
        name="add_student_new_fifth_civil_admin",
    ),
    path(
        "student_registration/view_fifth_civil_new/<int:student_id>",
        views.view_fifth_civil_new,
        name="view_fifth_civil_new",
    ),
    path(
        "student_registration/delete_document_new_fifth_civil/<int:student_id>",
        views.delete_document_new_fifth_civil,
        name="delete_document_new_fifth_civil",
    ),
    path(
        "student_registration/update_document_new_fifth_civil/<int:student_id>",
        views.update_document_new_fifth_civil,
        name="update_document_new_fifth_civil",
    ),
    path(
        "student_registration/student_list_new_sixth_civil",
        views.student_list_new_sixth_civil,
        name="student_list_new_sixth_civil",
    ),
    path(
        "student_registration/add_student_new_sixth_civil_admin",
        views.add_student_new_sixth_civil_admin,
        name="add_student_new_sixth_civil_admin",
    ),
    path(
        "student_registration/view_sixth_civil_new/<int:student_id>",
        views.view_sixth_civil_new,
        name="view_sixth_civil_new",
    ),
    path(
        "student_registration/delete_document_new_sixth_civil/<int:student_id>",
        views.delete_document_new_sixth_civil,
        name="delete_document_new_sixth_civil",
    ),
    path(
        "student_registration/update_document_new_sixth_civil/<int:student_id>",
        views.update_document_new_sixth_civil,
        name="update_document_new_sixth_civil",
    ),
    path("student_registration/student_list", views.student_list, name="student_list"),
    path(
        "student_registration/matched_fifth_year",
        views.match_burmese_data_fifth_year,
        name="matched_fifth_year",
    ),
    path(
        "student_registration/matched_sixth_year",
        views.match_burmese_data_sixth_year,
        name="matched_sixth_year",
    ),
    path(
        "student_registration/fifth_civil_list",
        views.student_list_fifth_civil,
        name="fifth_civil_list",
    ),
    path(
        "student_registration/add_student_old_fifth_civil_admin",
        views.add_student_old_fifth_civil_admin,
        name="add_student_old_fifth_civil_admin",
    ),
    path(
        "student_registration/delete_document_old_fifth_civil/<int:student_id>",
        views.delete_document_old_fifth_civil,
        name="delete_document_old_fifth_civil",
    ),
    path(
        "student_registration/update_document_old_fifth_civil/<int:student_id>",
        views.update_document_old_fifth_civil,
        name="update_document_old_fifth_civil",
    ),
    path(
        "student_registration/add_student_old_fifth_ec_admin",
        views.add_student_old_fifth_ec_admin,
        name="add_student_old_fifth_ec_admin",
    ),
    path(
        "student_registration/delete_document_old_fifth_ec/<int:student_id>",
        views.delete_document_old_fifth_ec,
        name="delete_document_old_fifth_ec",
    ),
    path(
        "student_registration/update_document_old_fifth_ec/<int:student_id>",
        views.update_document_old_fifth_ec,
        name="update_document_old_fifth_ec",
    ),
    path(
        "student_registration/add_student_old_fifth_ep_admin",
        views.add_student_old_fifth_ep_admin,
        name="add_student_old_fifth_ep_admin",
    ),
    path(
        "student_registration/delete_document_old_fifth_ep/<int:student_id>",
        views.delete_document_old_fifth_ep,
        name="delete_document_old_fifth_ep",
    ),
    path(
        "student_registration/update_document_old_fifth_ep/<int:student_id>",
        views.update_document_old_fifth_ep,
        name="update_document_old_fifth_ep",
    ),
    path(
        "student_registration/add_student_old_fifth_it_admin",
        views.add_student_old_fifth_it_admin,
        name="add_student_old_fifth_it_admin",
    ),
    path(
        "student_registration/delete_document_old_fifth_it/<int:student_id>",
        views.delete_document_old_fifth_it,
        name="delete_document_old_fifth_it",
    ),
    path(
        "student_registration/update_document_old_fifth_it/<int:student_id>",
        views.update_document_old_fifth_it,
        name="update_document_old_fifth_it",
    ),
    path(
        "student_registration/add_student_old_fifth_me_admin",
        views.add_student_old_fifth_me_admin,
        name="add_student_old_fifth_me_admin",
    ),
    path(
        "student_registration/delete_document_old_fifth_me/<int:student_id>",
        views.delete_document_old_fifth_me,
        name="delete_document_old_fifth_me",
    ),
    path(
        "student_registration/update_document_old_fifth_me/<int:student_id>",
        views.update_document_old_fifth_me,
        name="update_document_old_fifth_me",
    ),
    path(
        "student_registration/student_list_old_fifth_ec",
        views.student_list_old_fifth_ec,
        name="student_list_old_fifth_ec",
    ),
    path(
        "student_registration/student_list_old_fifth_ep",
        views.student_list_old_fifth_ep,
        name="student_list_old_fifth_ep",
    ),
    path(
        "student_registration/student_list_old_fifth_it",
        views.student_list_old_fifth_it,
        name="student_list_old_fifth_it",
    ),
    path(
        "student_registration/student_list_old_fifth_me",
        views.student_list_old_fifth_me,
        name="student_list_old_fifth_me",
    ),
    path(
        "student_registration/sixth_civil_list",
        views.student_list_sixth_civil,
        name="sixth_civil_list",
    ),
    path(
        "student_registration/student_list_old_sixth_ec",
        views.student_list_old_sixth_ec,
        name="student_list_old_sixth_ec",
    ),
    path(
        "student_registration/student_list_old_sixth_ep",
        views.student_list_old_sixth_ep,
        name="student_list_old_sixth_ep",
    ),
    path(
        "student_registration/student_list_old_sixth_it",
        views.student_list_old_sixth_it,
        name="student_list_old_sixth_it",
    ),
    path(
        "student_registration/student_list_old_sixth_me",
        views.student_list_old_sixth_me,
        name="student_list_old_sixth_me",
    ),
    path(
        "student_registration/add_student_old_sixth_civil_admin",
        views.add_student_old_sixth_civil_admin,
        name="add_student_old_sixth_civil_admin",
    ),
    path(
        "student_registration/delete_document_old_sixth_civil/<int:student_id>",
        views.delete_document_old_sixth_civil,
        name="delete_document_old_sixth_civil",
    ),
    path(
        "student_registration/update_document_old_sixth_civil/<int:student_id>",
        views.update_document_old_sixth_civil,
        name="update_document_old_sixth_civil",
    ),
    path(
        "student_registration/add_student_old_sixth_ec_admin",
        views.add_student_old_sixth_ec_admin,
        name="add_student_old_sixth_ec_admin",
    ),
    path(
        "student_registration/delete_document_old_sixth_ec/<int:student_id>",
        views.delete_document_old_sixth_ec,
        name="delete_document_old_sixth_ec",
    ),
    path(
        "student_registration/update_document_old_sixth_ec/<int:student_id>",
        views.update_document_old_sixth_ec,
        name="update_document_old_sixth_ec",
    ),
    path(
        "student_registration/add_student_old_sixth_ep_admin",
        views.add_student_old_sixth_ep_admin,
        name="add_student_old_sixth_ep_admin",
    ),
    path(
        "student_registration/delete_document_old_sixth_ep/<int:student_id>",
        views.delete_document_old_sixth_ep,
        name="delete_document_old_sixth_ep",
    ),
    path(
        "student_registration/update_document_old_sixth_ep/<int:student_id>",
        views.update_document_old_sixth_ep,
        name="update_document_old_sixth_ep",
    ),
    path(
        "student_registration/add_student_old_sixth_it_admin",
        views.add_student_old_sixth_it_admin,
        name="add_student_old_sixth_it_admin",
    ),
    path(
        "student_registration/delete_document_old_sixth_it/<int:student_id>",
        views.delete_document_old_sixth_it,
        name="delete_document_old_sixth_it",
    ),
    path(
        "student_registration/update_document_old_sixth_it/<int:student_id>",
        views.update_document_old_sixth_it,
        name="update_document_old_sixth_it",
    ),
    path(
        "student_registration/add_student_old_sixth_me_admin",
        views.add_student_old_sixth_me_admin,
        name="add_student_old_sixth_me_admin",
    ),
    path(
        "student_registration/delete_document_old_sixth_me/<int:student_id>",
        views.delete_document_old_sixth_me,
        name="delete_document_old_sixth_me",
    ),
    path(
        "student_registration/update_document_old_sixth_me/<int:student_id>",
        views.update_document_old_sixth_me,
        name="update_document_old_sixth_me",
    ),
    path(
        "student_registration/match_burmese_data",
        views.match_burmese_data,
        name="match_burmese_data",
    ),
    path(
        "student_registration/match_burmese_data_first_year",
        views.match_burmese_data_first_year,
        name="match_burmese_data_first_year",
    ),
    path("admin/", admin.site.urls),
]
